apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ include "chart.name" . }}
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
